### ISSUE TITLE
improve code to print token IDs

### ISSUE THREAD

**Issue by bibhas2** [rasbt/LLM-workshop-2024#5]
In ``02.ipynb`` the following code is being used to print the tokens and their IDs.

```python
for i, item in enumerate(vocab.items()):
    print(item)
    if i >= 50:
        break
```

It will be better if we do it like this:

```python
for token, id in vocab.items():
    print(token, id)

    if id > 50:
        break
```

This shows the actual IDs of the tokens and not the index returned by ``enumerate()``. This also doesn't assume any ordering in the dictionary.

**Comment by rasbt** [comment]
Hi there,

thanks for the suggestion. I like your version, but regarding the original version, it's just to print a few examples from the vocab for visualization purposes. The dictionaries should be ordered in any case though.

Aside from this being a good suggestion, I prefer it leave it as is, because otherwise the code will be different from the one in the video, which might be confusing.

Thanks for the comment, though!

**Comment by bibhas2** [comment]
I hear you, making the code different from the video will be confusing.

Perhaps an **errata** branch can be created with various enhancements and fixes if we find any.

**Comment by rasbt** [comment]
Yes, I agree, for mistakes, I'd also consider adding code comments directly in the notebook. (I would just not add optional things to avoid diverging too much.)
